### ISSUE TITLE
Update mod fields

### ISSUE THREAD

**Issue by XDelta** [astralchan/GifImporter#13]
Looks like your github handle changed, If you could update these fields in your mod for your next release
https://github.com/astralchan/GifImporter/blob/54224ad4ee5a59626f9f2d57e597a6b87ad7765c/GifImporter/GifImporter.cs#L22-L25

https://github.com/astralchan/GifImporter/blob/54224ad4ee5a59626f9f2d57e597a6b87ad7765c/GifImporter/GifImporter.cs#L33

-----
https://github.com/neos-modding-group/neos-mod-manifest/issues/184
https://github.com/neos-modding-group/neos-mod-manifest/pull/185

**Comment by astralchan** [comment]
updated in version 1.1.3 https://github.com/astralchan/GifImporter/releases/tag/1.1.3
