### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by epicEaston197** [astralchan/GifImporter#9]
The gift gets imported but it's on a single frame and its resolution isn't correct
![image](https://github.com/astralchan/GifImporter/assets/76523692/6a123bad-1512-4ecc-b53c-f72c2790a7fc)

**Comment by epicEaston197** [comment]
Importing this one does work but its resolution is still not correct
![image](https://github.com/astralchan/GifImporter/assets/76523692/64bd192c-aeaa-4f7a-a105-4a72a3d47dd1)
![spinning_lil_easton](https://github.com/astralchan/GifImporter/assets/76523692/c537cfb7-0bb8-4424-b42e-9382f6f34ca6)

**Comment by epicEaston197** [comment]
Found out why it isn't animating the `TimeIntDriver`is just not working for some reason
![image](https://github.com/astralchan/GifImporter/assets/76523692/7eb0eeff-bf27-40b8-a94e-f36bbab7c876)

**Comment by sjsanjsrh** [comment]
https://github.com/astralchan/GifImporter/pull/10 I fixed this bug

**Comment by astralchan** [comment]
Fixed in [790f7f4](https://github.com/astralchan/GifImporter/commit/790f7f49e3cad454f11b3209ece1beb4fc732a35) ( ty @sjsanjsrh )
